Repository statamic/cms, pull requests merged in 2021-07, with the labels that each got.

#3899 Make page tree collapsable
  resources/js/components/collections/View.vue
  resources/js/components/navigation/View.vue
  resources/js/components/structures/Branch.vue
  resources/js/components/structures/PageTree.vue
  resources/views/navigation/show.blade.php
  tailwind.config.js
Labels: enhancement

#3948 Have CollectionTreeStore ignore trees without a matching collection
  src/Stache/Stores/CollectionTreeStore.php
  tests/Stache/Stores/CollectionTreeStoreTest.php
Labels: bug

#3979 Fix Live Preview toolbar covering Bard toolbar
  resources/sass/components/fieldtypes/bard.scss
Labels: bug

#3975 Make sure media previews don’t overflow in the asset editor
  resources/js/components/assets/Editor/Editor.vue
  resources/sass/components/assets.scss
  src/Assets/Asset.php
Labels: bug

#3901 Delete trees when setting a collection to not orderable
  src/Http/Controllers/CP/Collections/CollectionsController.php
Labels: bug

#3964 Generate asset meta after updating the container contents
  src/Assets/AssetRepository.php
Labels: bug

#3950 Data list single select
  resources/js/components/data-list/Table.vue
Labels: enhancement

#3982 Add config field for default value
  resources/lang/en/messages.php
  src/Fieldtypes/ButtonGroup.php
  src/Fieldtypes/Checkboxes.php
  src/Fieldtypes/Floatval.php
  src/Fieldtypes/Hidden.php
  src/Fieldtypes/Html.php
  src/Fieldtypes/Integer.php
  src/Fieldtypes/Lists.php
  src/Fieldtypes/Markdown.php
  src/Fieldtypes/Radio.php
  src/Fieldtypes/Range.php
  src/Fieldtypes/Select.php
  src/Fieldtypes/Text.php
  src/Fieldtypes/Textarea.php
  src/Fieldtypes/Time.php
  src/Fieldtypes/Toggle.php
  src/Fieldtypes/Video.php
  src/Fieldtypes/Yaml.php
  tests/Fields/BlueprintTest.php
  tests/Fields/FieldsTest.php
  tests/Fields/SectionTest.php
  tests/Fieldtypes/NestedFieldsTest.php
Labels: enhancement

#3989 Prevent using reserved words as field handles
  resources/js/components/fields/Settings.vue
  resources/lang/en/validation.php
  src/Fields/Fields.php
  src/Fields/Validator.php
  src/Http/Controllers/CP/Fields/FieldsController.php
  tests/Fields/FieldsTest.php
Labels: bug, enhancement

#3978 Stop iframe from killing Vue in Safari
  resources/js/components/fieldtypes/VideoFieldtype.vue
Labels: bug

#3977 Throw a helpful exception if a referenced blueprint does not exist
  src/Exceptions/BlueprintNotFoundException.php
  src/Http/Controllers/CP/Collections/EntriesController.php
Labels: bug
