Repository statamic/cms, pull requests merged in 2021-06, with the labels that each got.

#3906 Entires fieldtype: check permissions for Create & Link Item button
  resources/js/components/inputs/relationship/RelationshipInput.vue
  src/Fieldtypes/Entries.php
Labels: bug

#3907 Multi-select DataList rows and Assets with shift key
  resources/js/components/assets/Browser/Browser.vue
  resources/js/components/data-list/Table.vue
Labels: enhancement

#3903 AlpineJS is here.
  package-lock.json
  package.json
  resources/js/app.js
  resources/sass/core/utilities.scss
  webpack.mix.js
Labels: dependencies

#3850 Update asset references when renaming or moving assets
  resources/js/components/fieldtypes/MarkdownFieldtype.vue
  src/Assets/Asset.php
  src/Assets/AssetContainer.php
  src/Assets/AssetReferenceUpdater.php
  src/Auth/File/User.php
  src/Fieldtypes/Bard.php
  src/Fieldtypes/Bard/Augmentor.php
  src/Fieldtypes/Bard/ImageNode.php
  src/Fieldtypes/Bard/StatamicImageNode.php
  src/Fieldtypes/Concerns/ResolvesStatamicUrls.php
  src/Fieldtypes/Markdown.php
  src/Globals/Variables.php
  src/Http/Resources/CP/Assets/Asset.php
  src/Listeners/UpdateAssetPaths.php
  src/Providers/EventServiceProvider.php
  src/Taxonomies/LocalizedTerm.php
  tests/Assets/UpdateAssetPathsTest.php
  tests/Fieldtypes/BardTest.php
  tests/Fieldtypes/MarkdownTest.php
Labels: enhancement

#3910 cmd+s is now just for quick saves
  resources/js/components/entries/PublishForm.vue
  resources/js/components/terms/PublishForm.vue
Labels: enhancement

#3900 Fix is_parent check by including the domain
  src/Tags/Structure.php
Labels: bug
